### ISSUE TITLE
About planned updates

### ISSUE THREAD

**Issue by schmunk42** [dmstr/yii2-db#7]
from README:

```
ActiveRecordAccessTrait
in cruds use select2 multi for inputs (domain, read, update, delete)
Setter: authItemArrayToString()
Getter: authItemStringToArray()
```

Can't we just use JSON here?

**Comment by Quexer69** [comment]
Use JSON would gives us no advantages IMHO.

Additionally would lead JSON instead of a simple CSV string to an new issue on find() !
https://github.com/dmstr/yii2-db/blob/master/db/traits/ActiveRecordAccessTrait.php#L73

I fixed the setter method in 61978dc so everything is ready for the use of the access trait in cruds with select2 multi dropdown lists.
